### ISSUE TITLE
Precompiling hangs on latest Julia nightly

### ISSUE THREAD

**Issue by robsmith11** [JuliaWeb/Mux.jl#150] opened 2023-02-07 05:00 UTC
I've let it run for 15 minutes before interrupting it:
```
julia> import Mux
 │ Package Mux not found, but a package named Mux is available from a registry.
 │ Install package?
 │   (@v1.10) pkg> add Mux
 └ (y/n/o) [y]:
    Updating registry at `/me/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/me/.julia/environments/v1.10/Project.toml`
  [a975b10e] + Mux v1.0.1
  No Changes to `/me/.julia/environments/v1.10/Manifest.toml`
Precompiling environment...
  Progress [>                                        ]  0/3
  ◒ Mux
^C Interrupted: Exiting precompilation...

  1 dependency had warnings during precompilation:
┌ Mux [a975b10e-0019-58db-a62f-e48ff68538c9]
│  [189278] signal (2): Interrupt
│  in expression starting at /me/.julia/packages/Mux/PipQ9/src/Mux.jl:35
│  lookup at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:122 [inlined]
│  may_contain_union_decision at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1452
│  may_contain_union_decision at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1438
│  may_contain_union_decision at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1438
│  may_contain_union_decision at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1438
│  may_contain_union_decision at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1454
│  may_contain_union_decision at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1438
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1461
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1511
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1511
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1511
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1511
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1511
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1511
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  local_forall_exists_subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1482
│  forall_exists_equal at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1510
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1388
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
│  subtype_unionall at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:864
│  subtype at /cache/build/default-amdci5-5/julialang/julia-master/src/subtype.c:1341
└
[ Info: Precompiling Mux [a975b10e-0019-58db-a62f-e48ff68538c9]
^C
```

**Comment by cmcaine** [comment] 2023-09-05 19:21
Closing: this seems like a bug in Julia that has now been fixed because I can't reproduce on my local builds of Julia 1.11 build or on v1.10.0-beta2.

If you can still reproduce this issue then please re-open and include `versioninfo()`. Thanks!

**Closed by cmcaine** 2023-09-05 19:21 UTC
